### ISSUE TITLE
Series of HTML closing tags rendering as text

### ISSUE THREAD

**Issue by caporta** [learn-co-curriculum/conditional-quiz-vowels#3]
In the last choice of the final quiz question, there appears to be a series of HTML closing tags that are being rendered as text. This seems inadvertent.

<img width="386" alt="screen shot 2015-08-18 at 12 31 18 am" src="https://cloud.githubusercontent.com/assets/10603933/9322409/7fc5d956-4540-11e5-842a-2f742b350220.png">

**Comment by AnnJohn** [comment]
@kvignali this seems to be an engineering issue

**Comment by ktravers** [comment]
@kvignali you can assign the new ticket to me

**Comment by AnnJohn** [comment]
@kvignali Has this been fixed or is there a deadline for it? Thanks

**Comment by ktravers** [comment]
hi @AnnJohn - i'm working on the fix for this here: https://github.com/flatiron-labs/ironboard/issues/3286. i'll clean up this specific lab tomorrow, but it'll take me a bit longer to suss out the underlying problem.

**Comment by AnnJohn** [comment]
Thanks @ktravers for the update

**Comment by ktravers** [comment]
@AnnJohn this lab has been cleaned up, and i have a fix open that'll hopefully prevent this from happening again. i'll let you know as soon as that fix is live on production (it's currently under review).

**Comment by ktravers** [comment]
@AnnJohn just merged in the fix, so this bug should be officially squashed :bug: :boom:  
of course, let me know if you see anything like this pop up again!

**Comment by AnnJohn** [comment]
@ktravers Thanks!
