### ISSUE TITLE
The Quiz is Wrong

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/conditional-quiz-vowels#4]
The question:

>What would the following statement return?

```ruby
letter = "b"

if letter == "a" || "e" || "i" || "o" || "u"
    "vowel"
else
   "not a vowel"
end
```

That would return `"vowel"` as they have string literals in the comparison. You'd have to repeat the `==` comparison on `letter`. So either this is a trick question, and the correct answer is `"vowel"` or it's wrong.

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by aviflombaum** [comment]
Thawing and assigning to @SophieDeBenedetto
