### ISSUE TITLE
Parsing Issue in Learn.co on Last Quiz Question

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/conditional-quiz-vowels#6]
![Issue](https://dl.dropboxusercontent.com/s/jtlu7r3unsljp1a/2015-09-04%20at%2011.45%20PM.png)

**Comment by matbalez** [comment]
@ktravers could you please take a look

**Comment by ktravers** [comment]
known issue: https://github.com/flatiron-labs/ironboard/issues/3286
i'll get this cleaned lab up tomorrow. still working on figuring out the underlying problem ... believe there's some faulty regex in the parser

**Comment by matbalez** [comment]
thanks kate

**Comment by AnnJohn** [comment]
@aviflombaum is this the same issue as #3 that was already raised?

**Comment by AnnJohn** [comment]
Resolution of #3, I think, resolved this one. Closing, but reopen if it didn't.
